### ISSUE TITLE
Mark repository as archived?

### ISSUE THREAD

**Issue by danielbachhuber** [goldenapples/shortcake-gutenberg#11]
@goldenapples @davisshaver @mattheu Should we mark this (and potentially other) repositories as archived?

(The reason I bring it up is that I've been receiving the security updates email for this repository, so thought I'd suggest it.)

**Comment by davisshaver** [comment]
Seems reasonable to me. Let's put this 🍰into the freezer.

**Comment by mattheu** [comment]
Yep I agree this has run its course 👍

**Comment by danielbachhuber** [comment]
@davisshaver @mattheu Just to be clear... do you mean only this repository, or all repositories in the organization?

Also, going to wait to hear from @goldenapples before pulling any triggers.

**Comment by goldenapples** [comment]
Oh! I agree 100% with archiving this repo as well as image-shortcake and shortcake-bakery. 

I know that some people are still using 🍰 https://github.com/wp-shortcake/shortcake, and occasionally submit patches, so I'm not totally sure there. But as nobody's been doing regular maintenance for a couple years, it's probably a good idea.

**Comment by danielbachhuber** [comment]
Cool. I'll go ahead and archive these three for now.
